# -*- coding: utf-8 -*-
"""DenoizingAndEstimation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t_25g3h4DFYUwBRf9NVD0W7EDZ4J-7qb
"""

import pandas as pd
import matplotlib.pyplot as plt
import scipy.signal as sig
import scipy.fft as FFT
import scipy.stats as stats
import numpy as np

"""#**Carga de datos**"""

dataF = pd.read_csv('TemperaCDMXEnero.csv')
#dataArr = dataF.to_string()
#print(dataArr)
print(dataF.info())

days = list(dataF['Día'])
means = list(dataF['Temperatura media [C]'])

#for day,meanTemp in zip(days,meanTemps):
#  print(day,'\t',meanTemp)

#plt.plot(days,means)
#plt.show()

"""#**Concatenacion de datos**"""

monthlyTemp = ['TemperaCDMXEnero.csv','TemperaCDMXFebrero.csv','TemperaCDMXMarzo.csv','TemperaCDMXAbril.csv']

days = []
means = []

for month in monthlyTemp:
  dataF = pd.read_csv(month)
  #print(dataF.info())
  days += list(dataF['Día'])
  means += list(dataF['Temperatura media [C]'])

"""Visualización de datos"""

print(plt.style.available)
plt.style.use('ggplot')

plt.plot(means)
plt.xlabel('Día')
plt.ylabel('Temperatura [C]')
plt.title('Temperatura media en CDMX')
plt.grid('both')
plt.show()

"""# Filtrado de datos"""

window_size = 12
x_ma = sig.lfilter([1/window_size]*window_size,[1],means)
#y = sig.convolve(means,[1/M]*M)

plt.plot(x_ma[window_size - 1:])
#plt.plot(y)
ax = plt.gca()
ax.set_xlim([0, 120])
ax.set_ylim([10, 23])
plt.xlabel('Día')
plt.ylabel('Temperatura [C]')
plt.title('Temperatura media en CDMX')
plt.grid('both')
plt.show()

#print(y)

numbers_series = pd.Series(means)
windows = numbers_series.rolling(window_size)

# Create a series of moving
# averages of each window
moving_averages = windows.mean()

# Convert pandas series back to list
moving_averages_list = moving_averages.tolist()

# Remove null entries from the list
final_list = moving_averages_list[window_size - 1:]

#print(final_list)
plt.plot(final_list)
ax = plt.gca()
ax.set_xlim([0, 120])
ax.set_ylim([10, 23])
plt.show()

plt.subplot(2,1,1)
plt.plot(means)
plt.title('Comparación de datos')
plt.ylabel('Temperatura [C]')
ax = plt.gca()
ax.set_xlim([0, 120])
ax.set_ylim([10, 23])

plt.subplot(2,1,2)
plt.plot(x_ma[window_size - 1:])
plt.xlabel('Día')
plt.ylabel('Temperatura [C]')
ax = plt.gca()
ax.set_xlim([0, 120])
ax.set_ylim([10, 23])

plt.show()

"""# **Analisis en frecuencia**"""

# Calculo del espectro de la senial
# Mean_k = np.fft.fft(x_np)
Means_k = FFT.fft(means, 128)
MeanFilt_k = FFT.fft([1/window_size]*window_size, 128)
X_ma_k = FFT.fft(x_ma, 128)

Means_k_mag = np.abs(Means_k)
MeanFilt_k_mag = np.abs(MeanFilt_k)
X_ma_k_mag = np.abs(X_ma_k)
#X_np_mag = np.abs(X_np)
#X_np_phase = np.angle(X_np)

plt.subplot(3,1,1)
plt.title('Espectro de los datos')
plt.plot(Means_k_mag[0:(128>>1) - 2])
#plt.plot(np.log(X_ma_k_mag[0:(128>>1) - 2]))

plt.subplot(3,1,2)
plt.plot(MeanFilt_k_mag[0:(128>>1) - 2])

plt.subplot(3,1,3)
plt.plot(X_ma_k_mag[0:(128>>1) - 2])
#plt.plot(np.log(X_ma_k_mag[0:(128>>1) - 2]))

plt.show()

"""# **Regresion lineal**"""

day_samps = [n for n in range(window_size-1,len(days))]
#day_samps = [n for n in range(len(days))]

res = stats.linregress(day_samps,x_ma[window_size - 1:])
#res = stats.linregress(day_samps,x_ma)

print('T = ',res.slope,"n +",res.intercept)

x_est = [res.slope*day +  res.intercept for day in day_samps]

plt.plot(day_samps, means[window_size - 1:],'*',label='Datos Originales')
plt.plot(day_samps, x_ma[window_size - 1:], 'o', label='Datos Filtrados')
#plt.plot(day_samps, x_ma, 'o', label='Datos Filtrados')
plt.plot(day_samps, x_est, 'r', label='Estimacion')
plt.xlabel('n (Día)')
plt.ylabel('Temperatura [C]')
plt.title('Temperatura media en CDMX')
plt.grid('both')
ax = plt.gca()
ax.set_xlim([0, 120])
ax.set_ylim([10, 23])
plt.legend()
plt.show()